### ISSUE TITLE
How to install on macOS

### ISSUE THREAD

**Issue by yoeran** [taoh/docker-machine-linode#8]
I would love to have Linode driver for Docker Machine on my Mac, but have not been able to install it correctly. Is there something I'm doing wrong or is there a "bug"?

I followed all the install instructions:
```
go get github.com/docker/machine
cd $GOPATH/src/github.com/docker/machine
make build

go get github.com/taoh/docker-machine-linode
cd $GOPATH/src/github.com/taoh/docker-machine-linode
make
make install
```

Everything runs correctly, except for the last `make install` command. It has the following output:

```
rm -f ./bin/docker-machine-driver-linode
rm -f /bin/docker-machine-driver-linode
GOGC=off go build -i -o ./bin/docker-machine-driver-linode ./bin
cp ./bin/docker-machine-driver-linode /bin/
cp: /bin/docker-machine-driver-linode: Operation not permitted
make: *** [install] Error 1
```

I also tried `sudo make install`, which didn't make a difference.
I'm on *macOS 10.12.3* with *Go1.8 darwin/amd64*

**Comment by basz** [comment]
seems you need to use sudo

**Comment by basz** [comment]
run this before doing `make install`

```
export GOPATH=`go env GOPATH`
mkdir -p $GOPATH/bin
```

**Comment by yoeran** [comment]
Ah, the `mkdir -p $GOPATH/bin` seems to have helped, thanks!
